---
- name: Git clone faketime from {{ faketime_repo }}
  git:
    repo: "{{ faketime_repo }}"
    dest: /tmp/faketime
    version: "{{ faketime_version }}"

- name: Make faketime
  make:
    chdir: /tmp/faketime

- name: Make install faketime
  become: true
  make:
    chdir: /tmp/faketime
    target: install

- name: Symlink faketime
  become: true
  file:
    state: link
    src: /usr/local/bin/faketime
    dest: /usr/bin/faketime
