---
- name: Git clone faketime
  git:
    repo: https://github.com/wolfcw/libfaketime.git
    dest: /tmp/faketime

- name: Make faketime
  make:
    chdir: /tmp/faketime

- name: Make install faketime
  become: true
  make:
    chdir: /tmp/faketime
    target: install
